name: Build and deploy a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/*'
      - 'kotlin-*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

env:
  SONATYPE_USERNAME: ${{ secrets.sonatype_username }}
  SONATYPE_PASSWORD: ${{ secrets.sonatype_password }}

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3
      - name: Cached Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 #v2
      - name: Set up JDK 17
        uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc #v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Check
        run: ./gradlew build check
        shell: bash
      - name: Upload
        run: ./gradlew publishAllPublicationsToOssrhStagingRepository -PgitRef=${{ github.ref }} -Psnapshot=true
        shell: bash
